version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-dev
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

  db:
    image: postgres
    container_name: postgeres-dev
    env_file:
      - ./db.env
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/postgres:/data/db
    ports:
      - "5432:5432"

networks:
  dev-network:
    driver: bridge
