version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-dev
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

  db:
    image: postgres
    container_name: postgeres-dev
    env_file:
      - ./db.env
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/postgres:/data/db
    ports:
      - "5432:5432"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-deepbio@deepbio.co.kr}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-deepbio}
  #   volumes:
  #     - ./data/dev/postgres:/data/db
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - dev-network
  #   restart: unless-stopped

networks:
  dev-network:
    driver: bridge
